[[headers]]
    for = "/*.js"
    [headers.values]
        Content-Encoding = "br"

[[headers]]
    for = "/*.css"
    [headers.values]
        Content-Encoding = "br"

[[headers]]
    for = "/*.html"
    [headers.values]
        Content-Encoding = "br"